/* ==========================================================================
   THE TABLE — dish data
   Each dish points at a placeholder image in public/images/ — swap these
   for real photography whenever you're ready (see README).
   ========================================================================== */

export const dishes = [
  {
    no: "01",
    title: "Heirloom Tomato & Basil Tart",
    medium: "Heirloom tomato, olive oil, thyme, shortcrust",
    note: "A study in concentric colour — the tomato is sliced thin enough to read as pigment rather than produce, arranged like a colour wheel across a blind-baked shell.",
    time: "1 hr 20 min",
    serves: "6",
    difficulty: "Easy",
    ingredients: [
      ["Shortcrust pastry, blind-baked", "1 (9in) shell"],
      ["Heirloom tomatoes, mixed colours", "700 g"],
      ["Fresh ricotta", "200 g"],
      ["Dijon mustard", "1 tbsp"],
      ["Olive oil", "3 tbsp"],
      ["Fresh thyme", "6 sprigs"],
      ["Flaky sea salt", "to taste"],
      ["Cracked black pepper", "to taste"],
    ],
    steps: [
      "Slice tomatoes into rounds, lay on paper towel and salt lightly. Let sit 20 minutes to draw out excess liquid.",
      "Blind-bake the shortcrust shell until golden. Let it cool fully before filling.",
      "Whisk ricotta with the mustard and a pinch of salt. Spread in an even layer across the base of the cooled shell.",
      "Pat the tomato slices dry, then layer them over the ricotta in loose concentric rings, alternating colours.",
      "Scatter thyme leaves over the top, drizzle with olive oil, and finish with flaky salt and pepper just before serving.",
    ],
    palette: { a: "#a15c3e", b: "#5b6146", c: "#e8d9b8" },
    image: "/images/plate-01.jpg",
  },
  {
    no: "02",
    title: "Charred Octopus, Lemon & Smoked Paprika",
    medium: "Octopus, lemon, smoked paprika, olive oil",
    note: "The char is the point, not the flaw — a hard sear against a slow braise gives a surface like scorched paper wrapped around something tender underneath.",
    time: "2 hr 30 min",
    serves: "4",
    difficulty: "Intermediate",
    ingredients: [
      ["Octopus, cleaned", "1.2 kg"],
      ["Bay leaves", "2"],
      ["Garlic cloves, smashed", "4"],
      ["Olive oil", "4 tbsp"],
      ["Smoked paprika", "1 tsp"],
      ["Lemon", "1, juiced and zested"],
      ["Flaky sea salt", "to taste"],
      ["Fresh parsley, chopped", "2 tbsp"],
    ],
    steps: [
      "Simmer the octopus gently with bay leaves and garlic for about 90 minutes, until a knife slides into the thickest part with no resistance.",
      "Cool the octopus in its liquid, then drain well and pat completely dry — this is what allows a proper char later.",
      "Cut into large pieces and toss with 2 tbsp olive oil and the smoked paprika.",
      "Sear hard in a very hot pan or on a grill, 2–3 minutes a side, until deeply charred at the edges.",
      "Rest briefly, then finish with lemon juice and zest, remaining olive oil, parsley, and flaky salt.",
    ],
    palette: { a: "#7a3b32", b: "#b08a4e", c: "#20180f" },
    image: "/images/plate-02.jpg",
  },
  {
    no: "03",
    title: "Brown Butter Sage Pappardelle",
    medium: "Pappardelle, brown butter, sage, parmesan",
    note: "Butter pushed just past caution — nutty, dark gold, and poured over ribbons wide enough to actually hold it.",
    time: "35 min",
    serves: "4",
    difficulty: "Easy",
    ingredients: [
      ["Fresh pappardelle", "450 g"],
      ["Unsalted butter", "115 g"],
      ["Fresh sage leaves", "14"],
      ["Parmesan, grated", "60 g"],
      ["Lemon zest", "1 tsp"],
      ["Flaky sea salt", "to taste"],
    ],
    steps: [
      "Bring a large pot of well-salted water to a boil and cook the pappardelle until just shy of al dente.",
      "Melt the butter in a wide pale-coloured pan over medium heat. Add the sage leaves once it begins to foam.",
      "Swirl the pan constantly as the butter turns from gold to a deep amber and smells nutty — pull it from the heat right as the milk solids brown, not blacken.",
      "Toss the drained pasta directly into the brown butter with a splash of pasta water to loosen the sauce.",
      "Plate with the crisped sage on top, a generous grating of parmesan, lemon zest, and flaky salt.",
    ],
    palette: { a: "#b08a4e", b: "#5b6146", c: "#e8d9b8" },
    image: "/images/plate-03.jpg",
  },
  {
    no: "04",
    title: "Roasted Stone Fruit, Honey & Thyme",
    medium: "Stone fruit, honey, thyme, crème fraîche",
    note: "Heat concentrates what raw fruit only implies — the sugars caramelise at the cut edge while the centre stays loose and warm.",
    time: "30 min",
    serves: "4",
    difficulty: "Easy",
    ingredients: [
      ["Peaches or plums, halved and pitted", "6"],
      ["Honey", "3 tbsp"],
      ["Fresh thyme", "4 sprigs"],
      ["Unsalted butter, small pieces", "2 tbsp"],
      ["Crème fraîche", "150 g"],
      ["Flaky sea salt", "a pinch"],
    ],
    steps: [
      "Heat the oven to 200°C (400°F). Arrange the fruit halves cut-side up in a baking dish.",
      "Drizzle with honey, scatter the thyme sprigs, and dot with butter.",
      "Roast 18–22 minutes, until the fruit is tender and the cut edges have caramelised.",
      "Let cool for 5 minutes — the residual heat finishes the centre without turning it to mush.",
      "Serve warm with a spoonful of crème fraîche and a pinch of flaky salt to cut the sweetness.",
    ],
    palette: { a: "#c98a5b", b: "#a15c3e", c: "#e8c9a8" },
    image: "/images/plate-04.jpg",
  },
  {
    no: "05",
    title: "Dark Chocolate & Olive Oil Torte",
    medium: "Dark chocolate, olive oil, espresso, sea salt",
    note: "No flour, no apology — a torte that stays dense and glossy because there is nothing in it to lighten it.",
    time: "1 hr, plus chilling",
    serves: "8",
    difficulty: "Intermediate",
    ingredients: [
      ["Dark chocolate (70%), chopped", "250 g"],
      ["Extra virgin olive oil", "120 ml"],
      ["Eggs", "4"],
      ["Sugar", "100 g"],
      ["Espresso, cooled", "2 tbsp"],
      ["Flaky sea salt", "to finish"],
    ],
    steps: [
      "Heat the oven to 160°C (325°F) and line an 8in round tin.",
      "Melt the chocolate and olive oil together gently, either over a double boiler or in short bursts in the microwave.",
      "Whisk the eggs and sugar until pale and roughly doubled in volume, about 4 minutes.",
      "Fold the melted chocolate and the espresso into the eggs in three additions, keeping as much air in the batter as you can.",
      "Bake 24–28 minutes, until the edges are set but the centre still holds a slight wobble. Cool fully, then chill at least 2 hours before slicing. Finish with flaky salt.",
    ],
    palette: { a: "#2a1a12", b: "#b08a4e", c: "#7a3b32" },
    image: "/images/plate-05.jpg",
  },
  {
    no: "06",
    title: "Herb-Crusted Lamb, Charred Leeks",
    medium: "Lamb rack, herb crust, charred leek",
    note: "A green crust holds the roast at the exact moment it leaves the oven, while the leeks are pushed toward collapse and blackened at the tips on purpose.",
    time: "1 hr 10 min",
    serves: "4",
    difficulty: "Intermediate",
    ingredients: [
      ["Lamb rack, frenched", "1 (8-bone)"],
      ["Fresh parsley, rosemary, thyme", "1 cup, mixed"],
      ["Garlic cloves", "3"],
      ["Dijon mustard", "2 tbsp"],
      ["Breadcrumbs", "60 g"],
      ["Olive oil", "3 tbsp"],
      ["Leeks, halved lengthwise", "4"],
      ["Flaky sea salt", "to taste"],
    ],
    steps: [
      "Heat the oven to 200°C (400°F). Season the lamb rack well and sear all sides in a hot pan until browned.",
      "Pulse the herbs, garlic, and breadcrumbs with 2 tbsp olive oil into a coarse paste.",
      "Brush the seared lamb with mustard, then press the herb mixture firmly over the fat side.",
      "Char the halved leeks cut-side down in a hot dry pan until well blackened at the edges, about 5 minutes.",
      "Roast the lamb 18–22 minutes for medium-rare, then rest 10 minutes before slicing between the bones. Serve over the charred leeks.",
    ],
    palette: { a: "#5b6146", b: "#7a3b32", c: "#2a1a12" },
    image: "/images/plate-06.jpg",
  },
];
