/* ==========================================================================
   Exhibition data
   Each exhibition is one "hang": a volume number, a status (current or
   archived), header copy, and a list of dishes. To add a new exhibition,
   copy the shape below and push it into the `exhibitions` array — the
   tab switcher and gallery pick up new entries automatically.
   ========================================================================== */

export const exhibitions = [
  {
    id: "vol-03",
    volume: "03",
    status: "current", // "current" | "archived"
    headingPlain: "Six dishes,",
    headingAccent: "hung like paintings.",
    intro:
      "A small collection of everyday cooking, treated with the same attention a gallery gives its walls. Every plate is labelled like a piece — medium, composition, and the recipe behind it — kept clean, minimal, and easy to actually cook from.",
    meta: {
      pieces: "06",
      category: "Seasonal, everyday",
      curatedFor: "Home kitchens",
    },
    dishes: [
      {
        no: "01",
        title: "Heirloom Tomato & Basil Tart",
        medium: "Heirloom tomato, olive oil, thyme, shortcrust",
        note: "A study in concentric colour — the tomato is sliced thin enough to read as pigment rather than produce, arranged like a colour wheel across a blind-baked shell.",
        time: "1 hr 20 min",
        serves: "6",
        difficulty: "Easy",
        ingredients: [
          ["Shortcrust pastry, blind-baked", "1 (9in) shell"],
          ["Heirloom tomatoes, mixed colours", "700 g"],
          ["Fresh ricotta", "200 g"],
          ["Dijon mustard", "1 tbsp"],
          ["Olive oil", "3 tbsp"],
          ["Fresh thyme", "6 sprigs"],
          ["Flaky sea salt", "to taste"],
          ["Cracked black pepper", "to taste"],
        ],
        steps: [
          "Slice tomatoes into rounds, lay on paper towel and salt lightly. Let sit 20 minutes to draw out excess liquid.",
          "Blind-bake the shortcrust shell until golden. Let it cool fully before filling.",
          "Whisk ricotta with the mustard and a pinch of salt. Spread in an even layer across the base of the cooled shell.",
          "Pat the tomato slices dry, then layer them over the ricotta in loose concentric rings, alternating colours.",
          "Scatter thyme leaves over the top, drizzle with olive oil, and finish with flaky salt and pepper just before serving.",
        ],
        palette: { a: "#a15c3e", b: "#5b6146", c: "#e8d9b8" },
        image: "/images/plate-01.jpg",
      },
      {
        no: "02",
        title: "Charred Octopus, Lemon & Smoked Paprika",
        medium: "Octopus, lemon, smoked paprika, olive oil",
        note: "The char is the point, not the flaw — a hard sear against a slow braise gives a surface like scorched paper wrapped around something tender underneath.",
        time: "2 hr 30 min",
        serves: "4",
        difficulty: "Intermediate",
        ingredients: [
          ["Octopus, cleaned", "1.2 kg"],
          ["Bay leaves", "2"],
          ["Garlic cloves, smashed", "4"],
          ["Olive oil", "4 tbsp"],
          ["Smoked paprika", "1 tsp"],
          ["Lemon", "1, juiced and zested"],
          ["Flaky sea salt", "to taste"],
          ["Fresh parsley, chopped", "2 tbsp"],
        ],
        steps: [
          "Simmer the octopus gently with bay leaves and garlic for about 90 minutes, until a knife slides into the thickest part with no resistance.",
          "Cool the octopus in its liquid, then drain well and pat completely dry — this is what allows a proper char later.",
          "Cut into large pieces and toss with 2 tbsp olive oil and the smoked paprika.",
          "Sear hard in a very hot pan or on a grill, 2–3 minutes a side, until deeply charred at the edges.",
          "Rest briefly, then finish with lemon juice and zest, remaining olive oil, parsley, and flaky salt.",
        ],
        palette: { a: "#7a3b32", b: "#b08a4e", c: "#20180f" },
        image: "/images/plate-02.jpg",
      },
      {
        no: "03",
        title: "Brown Butter Sage Pappardelle",
        medium: "Pappardelle, brown butter, sage, parmesan",
        note: "Butter pushed just past caution — nutty, dark gold, and poured over ribbons wide enough to actually hold it.",
        time: "35 min",
        serves: "4",
        difficulty: "Easy",
        ingredients: [
          ["Fresh pappardelle", "450 g"],
          ["Unsalted butter", "115 g"],
          ["Fresh sage leaves", "14"],
          ["Parmesan, grated", "60 g"],
          ["Lemon zest", "1 tsp"],
          ["Flaky sea salt", "to taste"],
        ],
        steps: [
          "Bring a large pot of well-salted water to a boil and cook the pappardelle until just shy of al dente.",
          "Melt the butter in a wide pale-coloured pan over medium heat. Add the sage leaves once it begins to foam.",
          "Swirl the pan constantly as the butter turns from gold to a deep amber and smells nutty — pull it from the heat right as the milk solids brown, not blacken.",
          "Toss the drained pasta directly into the brown butter with a splash of pasta water to loosen the sauce.",
          "Plate with the crisped sage on top, a generous grating of parmesan, lemon zest, and flaky salt.",
        ],
        palette: { a: "#b08a4e", b: "#5b6146", c: "#e8d9b8" },
        image: "/images/plate-03.jpg",
      },
      {
        no: "04",
        title: "Roasted Stone Fruit, Honey & Thyme",
        medium: "Stone fruit, honey, thyme, crème fraîche",
        note: "Heat concentrates what raw fruit only implies — the sugars caramelise at the cut edge while the centre stays loose and warm.",
        time: "30 min",
        serves: "4",
        difficulty: "Easy",
        ingredients: [
          ["Peaches or plums, halved and pitted", "6"],
          ["Honey", "3 tbsp"],
          ["Fresh thyme", "4 sprigs"],
          ["Unsalted butter, small pieces", "2 tbsp"],
          ["Crème fraîche", "150 g"],
          ["Flaky sea salt", "a pinch"],
        ],
        steps: [
          "Heat the oven to 200°C (400°F). Arrange the fruit halves cut-side up in a baking dish.",
          "Drizzle with honey, scatter the thyme sprigs, and dot with butter.",
          "Roast 18–22 minutes, until the fruit is tender and the cut edges have caramelised.",
          "Let cool for 5 minutes — the residual heat finishes the centre without turning it to mush.",
          "Serve warm with a spoonful of crème fraîche and a pinch of flaky salt to cut the sweetness.",
        ],
        palette: { a: "#c98a5b", b: "#a15c3e", c: "#e8c9a8" },
        image: "/images/plate-04.jpg",
      },
      {
        no: "05",
        title: "Dark Chocolate & Olive Oil Torte",
        medium: "Dark chocolate, olive oil, espresso, sea salt",
        note: "No flour, no apology — a torte that stays dense and glossy because there is nothing in it to lighten it.",
        time: "1 hr, plus chilling",
        serves: "8",
        difficulty: "Intermediate",
        ingredients: [
          ["Dark chocolate (70%), chopped", "250 g"],
          ["Extra virgin olive oil", "120 ml"],
          ["Eggs", "4"],
          ["Sugar", "100 g"],
          ["Espresso, cooled", "2 tbsp"],
          ["Flaky sea salt", "to finish"],
        ],
        steps: [
          "Heat the oven to 160°C (325°F) and line an 8in round tin.",
          "Melt the chocolate and olive oil together gently, either over a double boiler or in short bursts in the microwave.",
          "Whisk the eggs and sugar until pale and roughly doubled in volume, about 4 minutes.",
          "Fold the melted chocolate and the espresso into the eggs in three additions, keeping as much air in the batter as you can.",
          "Bake 24–28 minutes, until the edges are set but the centre still holds a slight wobble. Cool fully, then chill at least 2 hours before slicing. Finish with flaky salt.",
        ],
        palette: { a: "#2a1a12", b: "#b08a4e", c: "#7a3b32" },
        image: "/images/plate-05.jpg",
      },
      {
        no: "06",
        title: "Herb-Crusted Lamb, Charred Leeks",
        medium: "Lamb rack, herb crust, charred leek",
        note: "A green crust holds the roast at the exact moment it leaves the oven, while the leeks are pushed toward collapse and blackened at the tips on purpose.",
        time: "1 hr 10 min",
        serves: "4",
        difficulty: "Intermediate",
        ingredients: [
          ["Lamb rack, frenched", "1 (8-bone)"],
          ["Fresh parsley, rosemary, thyme", "1 cup, mixed"],
          ["Garlic cloves", "3"],
          ["Dijon mustard", "2 tbsp"],
          ["Breadcrumbs", "60 g"],
          ["Olive oil", "3 tbsp"],
          ["Leeks, halved lengthwise", "4"],
          ["Flaky sea salt", "to taste"],
        ],
        steps: [
          "Heat the oven to 200°C (400°F). Season the lamb rack well and sear all sides in a hot pan until browned.",
          "Pulse the herbs, garlic, and breadcrumbs with 2 tbsp olive oil into a coarse paste.",
          "Brush the seared lamb with mustard, then press the herb mixture firmly over the fat side.",
          "Char the halved leeks cut-side down in a hot dry pan until well blackened at the edges, about 5 minutes.",
          "Roast the lamb 18–22 minutes for medium-rare, then rest 10 minutes before slicing between the bones. Serve over the charred leeks.",
        ],
        palette: { a: "#5b6146", b: "#7a3b32", c: "#2a1a12" },
        image: "/images/plate-06.jpg",
      },
    ],
  },
  // Vol 03 ends here.
  {
    id: "vol-02",
    volume: "02",
    status: "archived",
    headingPlain: "Four plates,",
    headingAccent: "kept close to the fire.",
    intro:
      "An earlier hang, built around slow braises and things that spend a long time near heat. Kept here as reference rather than retired — the recipes still hold up.",
    meta: {
      pieces: "04",
      category: "Braises & roasts",
      curatedFor: "Sunday cooking",
    },
    dishes: [
      {
        no: "01",
        title: "Red Wine Braised Short Rib",
        medium: "Short rib, red wine, root vegetables",
        note: "Three hours of low heat until the meat gives before the fork does — the sauce is just what's left of the wine once it stops resisting.",
        time: "3 hr 15 min",
        serves: "4",
        difficulty: "Intermediate",
        ingredients: [
          ["Bone-in short ribs", "4 pieces"],
          ["Red wine", "500 ml"],
          ["Beef stock", "500 ml"],
          ["Carrots, roughly chopped", "3"],
          ["Onion, quartered", "1"],
          ["Garlic cloves", "4"],
          ["Tomato paste", "2 tbsp"],
          ["Fresh thyme", "4 sprigs"],
        ],
        steps: [
          "Season the ribs generously and sear on all sides in a heavy pot until deeply browned. Remove and set aside.",
          "Soften the onion, carrots, and garlic in the same pot, then stir in the tomato paste for a minute.",
          "Deglaze with the red wine, scraping up the browned bits, and let it reduce by roughly half.",
          "Return the ribs to the pot, add the stock and thyme, cover, and braise at 150°C (300°F) for about 3 hours.",
          "Rest the ribs in the sauce for 15 minutes before serving; skim the fat if needed.",
        ],
        palette: { a: "#6b3a2a", b: "#8a5a2e", c: "#241a12" },
        image: "/images/vol02-01.jpg",
      },
      {
        no: "02",
        title: "Roast Chicken, Charred Lemon",
        medium: "Whole chicken, lemon, garlic, herbs",
        note: "Nothing hidden — a whole bird roasted hot and fast, with the lemons pushed until they blacken instead of just softening.",
        time: "1 hr 20 min",
        serves: "4",
        difficulty: "Easy",
        ingredients: [
          ["Whole chicken", "1 (approx. 1.6 kg)"],
          ["Lemons, halved", "3"],
          ["Garlic head, halved", "1"],
          ["Olive oil", "3 tbsp"],
          ["Fresh rosemary", "4 sprigs"],
          ["Flaky sea salt", "to taste"],
        ],
        steps: [
          "Heat the oven to 220°C (425°F). Pat the chicken completely dry and season generously, inside and out.",
          "Stuff the cavity with the garlic head and one lemon half, then rub the skin all over with olive oil.",
          "Arrange the remaining lemon halves cut-side down around the chicken in the roasting pan.",
          "Roast 60–70 minutes, until the skin is deeply golden and the lemons have charred at the edges.",
          "Rest the chicken 10 minutes before carving; squeeze the charred lemon over the meat to serve.",
        ],
        palette: { a: "#8a5a2e", b: "#3a2f1a", c: "#c9a86a" },
        image: "/images/vol02-02.jpg",
      },
      {
        no: "03",
        title: "Slow White Beans, Rosemary Oil",
        medium: "White beans, rosemary, olive oil",
        note: "Beans given the time they actually need — the pot liquor thickens on its own into something worth spooning over bread.",
        time: "2 hr, plus soaking",
        serves: "6",
        difficulty: "Easy",
        ingredients: [
          ["Dried cannellini beans, soaked overnight", "400 g"],
          ["Olive oil", "4 tbsp"],
          ["Garlic cloves", "4"],
          ["Fresh rosemary", "3 sprigs"],
          ["Bay leaf", "1"],
          ["Flaky sea salt", "to taste"],
        ],
        steps: [
          "Drain the soaked beans and cover with fresh water by about 2 inches in a heavy pot.",
          "Add the garlic, bay leaf, and one rosemary sprig, and bring to a gentle simmer — not a boil.",
          "Cook uncovered for 90 minutes to 2 hours, topping up water as needed, until the beans are fully tender.",
          "Warm the olive oil with the remaining rosemary until fragrant, then strain to make a quick rosemary oil.",
          "Salt the beans generously once tender (not before), and finish each bowl with a spoonful of the rosemary oil.",
        ],
        palette: { a: "#4a4530", b: "#8a5a2e", c: "#d8cba8" },
        image: "/images/vol02-03.jpg",
      },
      {
        no: "04",
        title: "Baked Apples, Brown Sugar & Walnut",
        medium: "Apples, brown sugar, walnut, cinnamon",
        note: "The oven does the work a knife usually would — apples collapsed just enough to eat with a spoon, not a fork.",
        time: "45 min",
        serves: "4",
        difficulty: "Easy",
        ingredients: [
          ["Baking apples, cored", "4"],
          ["Brown sugar", "60 g"],
          ["Walnuts, chopped", "50 g"],
          ["Unsalted butter", "40 g"],
          ["Ground cinnamon", "1 tsp"],
          ["Vanilla ice cream", "to serve"],
        ],
        steps: [
          "Heat the oven to 190°C (375°F). Core the apples most of the way through, leaving the base intact.",
          "Mix the brown sugar, walnuts, and cinnamon, then pack the mixture into each apple's cavity.",
          "Top each apple with a small piece of butter and set them in a baking dish with a splash of water.",
          "Bake 30–35 minutes, until the apples are tender and the tops are caramelised.",
          "Serve warm with a scoop of vanilla ice cream melting into the cavity.",
        ],
        palette: { a: "#5a2f22", b: "#8a6a2e", c: "#2a1a12" },
        image: "/images/vol02-04.jpg",
      },
    ],
  },
  //Vol 02 ends here.
  {
    id: "vol-01",
    volume: "01",
    status: "archived",
    headingPlain: "10 dishes,",
    headingAccent: "a black and green affair.",
    intro:
      "An early exploration of matcha and food-grade charcoal across pastries, fresh pasta, desserts, and a few unexpected experiments. Kept here as an archive rather than retired—the recipes still hold up.",
    meta: {
      pieces: "10",
      category: "Pastries, pasta, desserts",
      curatedFor: "Weekend home bakers",
    },
    dishes: [
      {
        no: "01",
        title: "Matcha Gâteau de Tasse | Mug Cake",
        medium: "Matcha, flour, butter, sugar",
        note: "A simple mug cake that captures the essence of matcha in a convenient single-serving format.",
        time: "3.5 mins",
        serves: "2",
        difficulty: "Easy",
        ingredients: [
          ["Cake flour", "7 tbsp + 1 tsp"],
          ["Granulated sugar", "¼ cup"],
          ["Baking powder", "¼ tsp"],
          ["Baking soda", "⅛ tsp"],
          ["Salt", "⅛ tsp"],
          ["Matcha powder", "1 tsp"],
          ["Buttermilk | room temp", "⅓ cup"],
          ["Unsalted butter", "2 tbsp"],
          ["Egg | room temp", "1"],
          ["Vanilla extract", "½ tsp"],
          ["Toasted pecans | chopped", "2 tbsp"],
        ],
        steps: [
          "Combine all dry ingredients in a small bowl.",
          "In another bowl, gently whisk together the egg, melted butter, vanilla and buttermilk.",
          "Add the wet ingredient mixture to the flour/dry mixture and keep whisking to create a smooth, flow batter. Feel free to include pecans at this point.",
          "Divide butter into two microwave-safe mugs and fill them halfway. Drizzle extra toasted pecans on top.",
          "Microwave the mugs separately for 90 seconds on high heat. Add additional 10 second interval if cake hasn’t set yet. Do this until it’s cooked all the way through.",
          "Let it cool for 2 minutes.",
          "Serve warm with ice cream, maple syrup or a simple sift of powdered sugar.",
          "Enjoy!",
        ],
        palette: { a: "#6b3a2a", b: "#8a5a2e", c: "#241a12" },
        image: "/images/vol_01/vol01-01.webp",
      },
      {
        no: "02",
        title: "Almond Matcha Shortbread",
        medium: "Almonds, matcha, butter, sugar",
        note: "A delightful shortbread infused with the earthy flavor of matcha and the nutty richness of almonds.",
        time: "45mins - 1hr",
        serves: "12",
        difficulty: "Normal",
        ingredients: [
          ["Whole chicken", "1 (approx. 1.6 kg)"],
          ["Lemons, halved", "3"],
          ["Garlic head, halved", "1"],
          ["Olive oil", "3 tbsp"],
          ["Fresh rosemary", "4 sprigs"],
          ["Flaky sea salt", "to taste"],
        ],
        steps: [
          "Heat the oven to 220°C (425°F). Pat the chicken completely dry and season generously, inside and out.",
          "Stuff the cavity with the garlic head and one lemon half, then rub the skin all over with olive oil.",
          "Arrange the remaining lemon halves cut-side down around the chicken in the roasting pan.",
          "Roast 60–70 minutes, until the skin is deeply golden and the lemons have charred at the edges.",
          "Rest the chicken 10 minutes before carving; squeeze the charred lemon over the meat to serve.",
        ],
        palette: { a: "#8a5a2e", b: "#3a2f1a", c: "#c9a86a" },
        image: "/images/vol_01/vol01-02.webp",
      },
      {
        no: "03",
        title: "Slow White Beans, Rosemary Oil",
        medium: "White beans, rosemary, olive oil",
        note: "Beans given the time they actually need — the pot liquor thickens on its own into something worth spooning over bread.",
        time: "2 hr, plus soaking",
        serves: "6",
        difficulty: "Easy",
        ingredients: [
          ["Dried cannellini beans, soaked overnight", "400 g"],
          ["Olive oil", "4 tbsp"],
          ["Garlic cloves", "4"],
          ["Fresh rosemary", "3 sprigs"],
          ["Bay leaf", "1"],
          ["Flaky sea salt", "to taste"],
        ],
        steps: [
          "Drain the soaked beans and cover with fresh water by about 2 inches in a heavy pot.",
          "Add the garlic, bay leaf, and one rosemary sprig, and bring to a gentle simmer — not a boil.",
          "Cook uncovered for 90 minutes to 2 hours, topping up water as needed, until the beans are fully tender.",
          "Warm the olive oil with the remaining rosemary until fragrant, then strain to make a quick rosemary oil.",
          "Salt the beans generously once tender (not before), and finish each bowl with a spoonful of the rosemary oil.",
        ],
        palette: { a: "#4a4530", b: "#8a5a2e", c: "#d8cba8" },
        image: "/images/vol01-03.jpg",
      },
      {
        no: "04",
        title: "Baked Apples, Brown Sugar & Walnut",
        medium: "Apples, brown sugar, walnut, cinnamon",
        note: "The oven does the work a knife usually would — apples collapsed just enough to eat with a spoon, not a fork.",
        time: "45 min",
        serves: "4",
        difficulty: "Easy",
        ingredients: [
          ["Baking apples, cored", "4"],
          ["Brown sugar", "60 g"],
          ["Walnuts, chopped", "50 g"],
          ["Unsalted butter", "40 g"],
          ["Ground cinnamon", "1 tsp"],
          ["Vanilla ice cream", "to serve"],
        ],
        steps: [
          "Heat the oven to 190°C (375°F). Core the apples most of the way through, leaving the base intact.",
          "Mix the brown sugar, walnuts, and cinnamon, then pack the mixture into each apple's cavity.",
          "Top each apple with a small piece of butter and set them in a baking dish with a splash of water.",
          "Bake 30–35 minutes, until the apples are tender and the tops are caramelised.",
          "Serve warm with a scoop of vanilla ice cream melting into the cavity.",
        ],
        palette: { a: "#5a2f22", b: "#8a6a2e", c: "#2a1a12" },
        image: "/images/vol01-04.jpg",
      },
    ],
  },
];
